# Generated by Django 4.2.13 on 2024-05-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_options_cart_session_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='discounted_price',
        ),
    ]
