# Generated by Django 4.2.13 on 2024-05-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_original_price_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
