# Generated by Django 4.2.13 on 2024-06-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_anonymoususer'),
        ('store', '0007_alter_cart_product_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.anonymoususer'),
        ),
    ]
