# Generated by Django 4.2.13 on 2024-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_anonymous_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='anonymous_user',
        ),
    ]
