# Generated by Django 4.2.13 on 2024-06-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_payment_verified_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
