# Generated by Django 4.2.13 on 2025-02-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_color_size_productvariation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size')},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
