# Generated by Django 4.2.13 on 2025-02-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_productvariation_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the banner', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('desktop_image', models.ImageField(help_text='Upload desktop banner image', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Upload mobile banner image (optional)', null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this banner')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which banners are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
