# Generated by Django 4.2.13 on 2025-02-09 01:29

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(help_text='Upload desktop banner image', upload_to=store.models.getFileName),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Upload mobile banner image (optional)', null=True, upload_to=store.models.getFileName),
        ),
    ]
