# Generated by Django 4.2.13 on 2025-02-19 23:03

from django.db import migrations
import imagekit.models.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_heroslide_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=store.models.getFileName),
        ),
    ]
