# Generated by Django 4.2.13 on 2024-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_anonymous_user'),
        ('user', '0002_anonymoususer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
