# Generated by Django 4.2.13 on 2025-03-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_address_user_bio_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
