# Generated by Django 4.2.13 on 2025-03-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
